# NumPy Practice

This notebook offers a set of excercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documnetation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [16]:
# Create a 1-dimensional NumPy array using np.array()
a1 = np.array([1, 2, 3])

# Create a 2-dimensional NumPy array using np.array()
a2 = np.array([[1, 2.5, 6], 
              [23, 44, 0.5]])

# Create a 3-dimensional Numpy array using np.array()
a3 = np.array([[[1, 2, 3], [2, 3, 4], [3, 4, 5]], 
              [[1, 3, 2], [2, 4, 5], [3, 7, 6]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [5]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
a1.shape, a1.ndim, a1.dtype, a1.size, type(a1)

((3,), 1, dtype('int64'), 3, numpy.ndarray)

In [6]:
# Attributes of 2-dimensional array
a2.shape, a2.ndim, a2.dtype, a2.size, type(a2)

((2, 3), 2, dtype('float64'), 6, numpy.ndarray)

In [17]:
# Attributes of 3-dimensional array
a3.shape, a3.ndim, a3.dtype, a3.size, type(a3)

((2, 3, 3), 3, dtype('int64'), 18, numpy.ndarray)

In [18]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
df2 = pd.DataFrame(a2, 
                  index=["Prima Riga","Seconda Riga"], 
                  columns=["Ventordici", "Quinsedici", "Trisette"])

In [19]:
df2

Ventordici  Quinsedici  Trisette
Prima Riga           1.0         2.5       6.0
Seconda Riga        23.0        44.0       0.5

In [32]:
# Create an array of shape (10, 2) with only ones
ones = np.ones((10,2))
ones.shape

(10, 2)

In [26]:
# Create an array of shape (7, 2, 3) of only zeros
zeros = np.zeros((7, 2, 3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [43]:
# Create an array within a range of 0 and 100 with step 3
a_range = np.arange(0, 100, 3)
a_range

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [47]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
a_random = np.random.randint(0, 10, size=(7,2))
a_random

array([[3, 7],
       [6, 8],
       [7, 4],
       [1, 4],
       [7, 9],
       [8, 8],
       [0, 8]])

In [39]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
a_random_2 = np.random.random((3,5))
a_random_2.shape

(3, 5)

In [49]:
# Set the random seed to 42
np.random.seed(seed=42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
a_random_3 = np.random.randint(0, 10, size=(4,6))
a_random_3

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [51]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
a_random_4 = np.random.randint(1, 10, size=(3,7))
a_random_4
# Find the unique numbers in the array you just created
np.unique(a_random_4)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
a_random_4

array([[7, 8, 3, 1, 4, 2, 8],
       [4, 2, 6, 6, 4, 6, 2],
       [2, 4, 8, 7, 9, 8, 5]])

In [57]:
# Find the 0'th index of the latest array you created
a_random_4[0, 0]

7

In [56]:
# Get the first 2 values of the first 2 rows of the latest array
a_random_4[:2, :2]

array([[7, 8],
       [4, 2]])

In [63]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
ar = np.random.randint(0, 10, size=(3,5))
ao = np.ones((3,5))

In [64]:
ar

array([[2, 5, 1, 9, 8],
       [4, 5, 3, 9, 6],
       [8, 6, 0, 0, 8]])

In [65]:
ao

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [67]:
# Add the two arrays together
ar + ao

array([[ 3.,  6.,  2., 10.,  9.],
       [ 5.,  6.,  4., 10.,  7.],
       [ 9.,  7.,  1.,  1.,  9.]])

In [69]:
# Create another array of ones of shape (5, 3)
ao2 = np.ones((5,3))
ao2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [71]:
# Try add the array of ones and the other most recent array together
ao + ao2.T

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [72]:
# Create another array of ones of shape (3, 5)
ao3 = np.ones((3,5))

In [76]:
ao.shape, ao2.shape, ao3.shape

((3, 5), (5, 3), (3, 5))

In [75]:
# Subtract the new array of ones from the other most recent array
ao - ao3

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [82]:
# Multiply the ones array with the latest array
ao * ar

array([[2., 5., 1., 9., 8.],
       [4., 5., 3., 9., 6.],
       [8., 6., 0., 0., 8.]])

In [80]:
# Take the latest array to the power of 2 using '**'
ar ** 2

array([[ 4, 25,  1, 81, 64],
       [16, 25,  9, 81, 36],
       [64, 36,  0,  0, 64]])

In [81]:
# Do the same thing with np.square()
np.square(ar)

array([[ 4, 25,  1, 81, 64],
       [16, 25,  9, 81, 36],
       [64, 36,  0,  0, 64]])

In [83]:
# Find the mean of the latest array using np.mean()
np.mean(ar)

4.933333333333334

In [84]:
# Find the maximum of the latest array using np.max()
np.max(ar)

9

In [85]:
# Find the minimum of the latest array using np.min()
np.min(ar)

0

In [86]:
# Find the standard deviation of the latest array
np.std(ar)

3.0652170486860397

In [87]:
# Find the variance of the latest array
np.var(ar)

9.395555555555555

In [91]:
ar

array([[2, 5, 1, 9, 8],
       [4, 5, 3, 9, 6],
       [8, 6, 0, 0, 8]])

In [90]:
# Reshape the latest array to (3, 5, 1)
ar.reshape((3,5,1))

array([[[2],
        [5],
        [1],
        [9],
        [8]],

       [[4],
        [5],
        [3],
        [9],
        [6]],

       [[8],
        [6],
        [0],
        [0],
        [8]]])

In [94]:
# Transpose the latest array
ar.T

array([[2, 4, 8],
       [5, 5, 6],
       [1, 3, 0],
       [9, 9, 0],
       [8, 6, 8]])

What does the transpose do?

In [96]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
ar1 = np.random.randint(0,10,size=(3,3))
ar1

array([[0, 2, 9],
       [7, 5, 7],
       [8, 3, 0]])

In [98]:
ar2 = np.random.randint(0,10, size=(3,2))
ar2

array([[0, 4],
       [0, 7],
       [0, 0]])

In [99]:
ar1.shape, ar2.shape

((3, 3), (3, 2))

In [100]:
# Perform a dot product on the two newest arrays you created
ar1.dot(ar2)

array([[ 0, 14],
       [ 0, 63],
       [ 0, 53]])

In [101]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
ar3 = np.random.randint(0,10,size=(4,3))
ar3

array([[1, 1, 5],
       [6, 4, 0],
       [0, 2, 1],
       [4, 9, 5]])

In [102]:
ar4 = np.random.randint(0,10,size=(4,3))
ar4

array([[6, 3, 6],
       [7, 0, 5],
       [7, 4, 3],
       [1, 5, 5]])

In [104]:
ar3.shape, ar4.shape

((4, 3), (4, 3))

In [106]:
# Perform a dot product on the two newest arrays you created
ar3.dot(ar4.T)

array([[39, 32, 26, 31],
       [48, 42, 58, 26],
       [12,  5, 11, 15],
       [81, 53, 79, 74]])

It doesn't work. How would you fix it?

In [107]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
ar3.dot(ar4.T)

array([[39, 32, 26, 31],
       [48, 42, 58, 26],
       [12,  5, 11, 15],
       [81, 53, 79, 74]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [110]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
ar5 = np.random.randint(0, 10, size=(3,2))
ar5

array([[0, 8],
       [5, 2],
       [3, 3]])

In [111]:
ar6 = np.random.randint(0, 10, size=(3,2))
ar6

array([[2, 9],
       [2, 2],
       [3, 6]])

In [112]:
# Compare the two arrays with '>'
ar5 > ar6

array([[False, False],
       [ True, False],
       [False, False]])

What happens when you compare the arrays with `>`?

In [113]:
# Compare the two arrays with '>='
ar5 >= ar6

array([[False, False],
       [ True,  True],
       [ True, False]])

In [114]:
# Find which elements of the first array are greater than 7
ar5 > 7

array([[False,  True],
       [False, False],
       [False, False]])

In [115]:
# Which parts of each array are equal? (try using '==')
ar5 == ar6

array([[False, False],
       [False,  True],
       [ True, False]])

In [116]:
# Sort one of the arrays you just created in ascending order
np.sort(ar5)

array([[0, 8],
       [2, 5],
       [3, 3]])

In [117]:
# Sort the indexes of one of the arrays you just created
np.argsort(ar5)

array([[0, 1],
       [1, 0],
       [0, 1]])

In [118]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(ar5)

1

In [119]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(ar5)

0

In [122]:
ar5

array([[0, 8],
       [5, 2],
       [3, 3]])

In [121]:
ar5.shape

(3, 2)

In [120]:
# Find the indexes with the maximum values down the verticial axis
# of one of the arrays you created
np.argmax(ar5, axis=1)

array([1, 0, 0])

In [123]:
# Find the indexes with the minimum values across the horizontal axis
# of one of the arrays you created
np.argmin(ar5, axis=0)

array([0, 1])

In [126]:
# Create an array of normally distributed random numbers
ar_n = np.random.normal(size=(3,2))
ar_n

array([[ 0.62054822, -0.16093738],
       [-0.3882644 , -0.88551237],
       [-0.35674503,  0.5561218 ]])

In [130]:
# Create an array with 10 evenly spaced numbers between 1 and 100
ar_s = np.linspace(1, 100, num=10)
ar_s

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://docs.scipy.org/doc/numpy-1.15.0/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.